### ISSUE TITLE
Drop requirements.txt file

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#182]
As mentioned in #140 , `requirements.txt` and `test-requirements.txt` are not exactly support anymore. Should we stop generating this files and instruct the user to just `setup.cfg` directly?

**Comment by FlorianWilhelm** [comment]
Maybe we should in a version 3.1 first add a `--no-req-file` flag and wait for the complete removal until version 4.0 (due to semantic versioning). Also we need to discuss if we rather advocate the usage of pipenv or something else. Definitely I think we should have the separation of unpinned requirements and pinned requirements as discussed in #140. From my experience it's extremely important for production to have a clean separation for that in order to guarantee reproducibility and at the same time avoid the dependency hell.

**Comment by FlorianWilhelm** [comment]
Removed in f8803392fab2e6b40d360cebe68616f868ae253a
