### ISSUE TITLE
Proposal: a Template for custom extensions

### ISSUE THREAD

**Issue by chobeat** [pyscaffold/pyscaffold#208]
Hello guys,

yesterday I was thinking about the custom extension I wrote for my company and how to frame my use case. I thought back about your documentation on how to create a custom extension and while it's not so difficult, I realized that all that knowledge could be easily transfered into a pyscaffold extension. So basically a template to create a project that is ready to be filled with some logic to customize the extension. This process now is not super complicated but you need to figure out the namespace thing and you need to find what exactly you need to extend and how. A class could be provided, already in the right namespace and with the proper structure, maybe implementing already some very common pattern. One could be simply picking up files from a "resource" directory and copy them in the newly created project, so that the most common use case (adding new files and templates) requires the user to simply move files into the extension/resource folder.

Does it make sense?

**Comment by FlorianWilhelm** [comment]
Cool idea! Have you had a look at the [pyscaffoldext-pyproject](https://github.com/pyscaffold/pyscaffoldext-pyproject) extension? Since this is is so simple it serves me right now as template for other extensions. If you want I can give you access to the PyScaffold Github organisation and you can create a repo for a PyScaffold extension template.

**Comment by chobeat** [comment]
Ah ok, no, I guess that covers most of my ideas. I think I've seen it but I didn't use it as a template for my project. I just took inspiration from it and copy-pasted some pieces. Also that's the way it's presented in the documentation but maybe presenting it in the docs in a different way might suffice to give the right value to that extension. These are just my 2 cents, coming from a fresh experience with this whole process but I'm not sure my experience is the most common one.

**Comment by FlorianWilhelm** [comment]
@chobeat We are always looking for exactly the kind of feedback you are providing. How would you present it in the documentation such that it is easier for beginners to PyScaffold? You can also provide a PR if you want to. We are looking forward to your valuable input! Thanks in advance.

**Comment by chobeat** [comment]
Ok, nevermind, I missread the documentation for that extension. I thought the command there (that I didn't read) was to create the entire structure, not just to bootstrap the project. In fact I was a bit surprised at first that I didn't use it in the first place. (never review this stuff from the office).

That said, I go back to my initial point: this stuff can be packaged in a dedicated command and this command might make that example sort of "obsolete". 

If you want to give me access to the organization, I would gladly like to work on that in a dedicated repo. I think my understanding of pyscaffold is still too superficial to reach the goal on my own but I can try and learn while doing.

**Comment by FlorianWilhelm** [comment]
@chobeat Okay, cool, you should have an invitation.

**Comment by chobeat** [comment]
ok guys, I created the first draft of the extension. You can find it on master. From now on I will work with incremental changes through PRs and I would like some suggestions on how to write the code more pyscaffoldingly and  have requests for things you believe should be there.

So far it's all quite simple but working on two different layers of content generation makes me stupid so I would like some external validation on the general direction I'm taking.

**Comment by FlorianWilhelm** [comment]
@chobeat, thanks for your contribution. I got several questions:
1) You have not yet added any documentation. Also in `templates/__init__.py` you seem to define more templates then exist?
2) Have you read our coding style standards? We use flake8 https://pyscaffold.org/en/latest/contributing.html#code-contributions
3) Why do you replace `setup.py`?

I have to test it some more.

**Comment by chobeat** [comment]
1) Yes, I will clean it up, you're right
2) Ok, I will work on it
3) Because in the old version, there was a conflict with the definition of the entry points. I see that it has been fixed so yeah, probably I don't need the setup.py thing anymore.

**Comment by chobeat** [comment]
Ok, I've implemented the changes in a branch. Let me know if you can think of more improvements.

One that I was thinking about was to add a template folder with one template, one function doing the substitutions and an action adding the file to the structure, basically replicating the structure of `custom-extension` itself but with a "dummy" template instead.

**Comment by abravalheri** [comment]
@chobeat thank you very much!

What do you think of including `pre-commit` and `travis` in the repository itself (as if it was generated by running `putup --tavis --pre-commit ...`)? I think it can help to solve @FlorianWilhelm 2nd point.

It would also be nice in the future to include a very basic skeleton for the tests (is always a good practice to incentivize people to write automatic tests). I can help with that. What do you think?

**Comment by chobeat** [comment]
ok, I will add travis and precommit. For the testability I would like to receive some pointes: what should I test beyond actual structure manipulation? Is there a reliable way to test that the extension will be picked up by `putup`? Right now I'm working with a Dockerfile but for sure it's not the best way.

**Comment by abravalheri** [comment]
@chobeat, right now we are just testing the structure change and if all the files are being created... I think [`text_tox`](https://github.com/blue-yonder/pyscaffold/blob/master/tests/extensions/test_tox.py) is a good example (actually most of the extensions right now are being tested that way). I can provide you also a PR with a template for tests being generated by the extension itself.

Regarding the second question, I think `tox`  is enough, everything should run inside an isolated venv, and the package itself is installed before the tests run, so setuptools entrypoints should be available...

**Comment by chobeat** [comment]
I've added travis but I think it needs to be activated by the organization admin.

**Comment by FlorianWilhelm** [comment]
Since I just started to work on another PyScaffold extension for data science projects, I must say that I was repeating a lot of things that I did in the markdown extension. Therefore, I think @chobeat proposal is really great and would say that we should have this extension done for the release of PyScaffold 3.2. One point is that we should clarify maybe in text form before what the extension should actually do. Here is my proposal:

Let's say I want to create a data science extension with the name `dsproject` I would love to be able to just do `putup dsproject --custom-extension`. This should do the following.

1. Set the actual project name to `pyscaffoldext-dsproject` while keeping the package name `dsproject`,
2. Set the namespace parameter to `pyscaffoldext`,
3. Activate the option `--no-skeleton` as well as `--pre-commit` and `--tox` since we want *clean-coded* extensions,
4. Create a Python module `extension.py` holding a basic extension class called `DSProject` (just make sure the first letter is capital) within the `dsproject` package as well as a template folder with `__init__.py` similar to how it is done in `pyscaffoldext-markdown`.
5. Make some sane settings in `setup.cfg` like:
     * set `setup_requires = pyscaffold>=3.1a0,<3.2a0` (use the functions from PyScaffold for that!)
     * set `install_requires = pyscaffold>=3.1a0,<4.0a0`
     * set the proper entry_point: 
           ```
           pyscaffold.cli =
                 dsproject = pyscaffoldext.markdown.extension:DSProject
           ```
    

I guess, 1. till 3. can be done easily by registering a function before the structure is created that just sets the options in `opts` accordingly. 4. and 5. are performed in another registered functions after the structure was created and should not be that difficult either.

@chobeat and @abravalheri: What do you think about that? Do you have corrections, objections and/or extensions?

**Comment by chobeat** [comment]
3) one comment: right now I see you never call `super().activate` in any action and this hinders composability. It works for one extension (I do it with NoSkeleton) but  I guess it doesn't work with multiple. I'm not an OO fanatic but I think this would be nice for the user in general to compose extensions this way. Or is there some kind of helper for this?

**Comment by chobeat** [comment]
2) the namespace is just a matter of consistency or there might be problems not setting it? How can I test if it breaks? Is the key in opts `namespace`?

**Comment by FlorianWilhelm** [comment]
@chobeat, I guess we should fix that with `super().activate` (if @abravalheri agrees and shares your concerns) but in general I am not a big fan of multiple inheritance and all the trouble you can have with the MRO. Also what you describe is no composition but inheritance and I don't understand why you actually need it. If you want to activate the `NoSkeleton` extension then why don't you just set it in `opts`? This would be way more explicit and easier to understand compared to inheriting from each extension you want to activate. 

BTW, also `namespace` is inside of `opts`. We use namespaces to avoid clashes with other packages that might have the same name. Thus I can easily create a `markdown` package that surely already exists on PyPI because mine will be inside the `pyscaffoldext` namespace and the distribution itself is called `pyscaffoldext-markdown`. In principle we don't need this namespace but it's a nice convention that helps us.

**Comment by FlorianWilhelm** [comment]
BTW, inside the current `pyscaffoldext` namespace you now have a `pyscaffoldext_custom_extension` package and a `custom_extension` package. You should actually have only the latter one.

**Comment by chobeat** [comment]
I would to work on the 5. but I'm not sure which functions I should use.

**Comment by FlorianWilhelm** [comment]
@chobeat Use `configupdater` for setting the values and for the first one you could use `pyscaffold.update.get_setup_requires_version` I guess.  Look around `pyscaffold.update` and you might find things you can use for the task.

**Comment by chobeat** [comment]
@FlorianWilhelm the point 5.1 looks already covered by the standard pyscaffold versioning. How does it differ from the standard behavior?

**Comment by FlorianWilhelm** [comment]
@chobeat, yes, my bad, this is already covered.

**Comment by chobeat** [comment]
and what's the point of having 5.2 then? I thought one implied the other (but I'm not sure)

**Comment by abravalheri** [comment]
Sorry for the delay guys. I think you are already over this by I agree with @FlorianWilhelm about `super().activate`. It is more an interface that must be implemented for the "abstract class" to work, not exactly a inheritance chain, and I believe that if we call it, we will get back a `NotImplementedError`.

@chobeat, the point 5.2 is important because we are going to need PyScaffold installed at runtime for the extension to work.

5.1 only means that you need PyScaffold during "packaging time", or in other words, when running `python setup.py ...`. This way the dev can use PyScaffold to create a package, upload it to PyPI, but when someone else installs it with `pip`, this other person will not end up unnecessarily downloading PyScaffold and s a dependency... (this is a bit hard to explain, sorry if that is not clear)

**Comment by chobeat** [comment]
No, it's clear. I think I've always used it correctly but for some reason it didn't make sense in this context but now it's clear.

**Comment by FlorianWilhelm** [comment]
Hi @chobeat, I will take a look at the extension in the next few days. After that I will restructure the extensions section of PyScaffold a bit to provide a comprehensible list of available extensions including yours of course.

**Comment by FlorianWilhelm** [comment]
@chobeat, I just uploaded a first version of the extension to [PyPI](https://pypi.org/project/pyscaffoldext-custom-extension/). Thanks for your work!
Still I think there are a few more things to do to make it even more useful. I will add some PRs and issue directly in the repo of the extension.

Also one note regarding the git history. Often it makes sense to use `git rebase` to have a linear line of commits.

**Comment by chobeat** [comment]
I'm not a fan of `rebase` but `rebase` vs `merge` is the new `tab` vs `spaces` so I don't want to discuss it. If you prefer a rebase or squashed history, I will do it from now on.

**Comment by chobeat** [comment]
I don't have strong opinions on any of the options. I use merge because I'm more used to it and because when you have many people contributing, it's easier to reconstruct what happened when something goes wrong, but if I'm alone, yeah, I have no argument against rebase.

**Comment by chobeat** [comment]
Ok, are we done or am I missing something?

**Comment by FlorianWilhelm** [comment]
@chobeat, yes, I guess we have a first version now and I'll push the current state as v0.2 today. Still there is a lot more polishing to do and I'll add the corresponding issues in the repo of the plugin. For instance, we do follow the Google docstring style for PyScaffold and thus also the official plugin should lead by example.
