### ISSUE TITLE
Remove support for Python 3.4

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#226]
## Describe your use-case
Python 3.4 reaches end of lifetime march 2019. After that the support for it can be safely removed.

**Comment by FlorianWilhelm** [comment]
Done in 7a8dc16288f83bafa05a496bfb2ca6ce3ed1d11c

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, do you think the best is to fast-forward to 3.6, instead of 3.5?
Ubuntu (which is very popular) and other distros I suspect, still support 3.5
(see 16.06 LTS https://ubuntu.com/about/release-cycle and https://packages.ubuntu.com/xenial/python3).

**Comment by FlorianWilhelm** [comment]
Hm... good point, the end of life for Python 3.5 is 2020-09-13 and so far major versions like PyScaffold needed more than one year as I have little time, that's why I thought it will surely take some time for PyScaffold 4.0. What would be your time estimation with the current feature set we have?

**Comment by abravalheri** [comment]
It's hard to estimate... 
If we just have to rewrite how `name` and `project-path` work, allow in-place updates, and change the namespace to create empty `__init__.py` , it might be OK, but one never know (specially because we need to make the extensions compatible as well).

Can we do something like officially supporting 3.6 (included in the docs), but not enforce it in `setup_requires`? This way even if we release PyScaffold 4.0 closer to the end of life of Python 3.5, we don't have to release a following major version just to drop the support and be consistent with semantic versioning.

**Comment by FlorianWilhelm** [comment]
@abravalheri, good points. That's fine for me, so you can just switch back to Python 3.5 in setup.cfg and the template for it as well I guess.
