### ISSUE TITLE
More docs on versions

### ISSUE THREAD

**Issue by shimbalama** [pyscaffold/pyscaffold#227]
Hi,

I've tried to add a project to pip and got 'HTTPError: 400 Client Error: '0.0.post0.dev5+gc5da6ad' is an invalid value for Version. Error: Can't use PEP 440 local versions'.

Can you please flesh out your docs on how to be PEP 440 compliant? Or point me to somewhere where it's explained in the context of pyscaffold?

Thanks in advance,
Liam

**Comment by FlorianWilhelm** [comment]
Hi @shimbalama, it's actually explained [here](https://pyscaffold.org/en/latest/features.html#complete-git-integration) with a link to the definition of PEP440. By `adding your project to pip` you mean uploading to PyPI I guess. I will add a sentence that PyPI does not allow local versions which is the `+gc5da6ad` part in your case. That means you can only upload tagged versions for practical reasons.

**Comment by FlorianWilhelm** [comment]
I added in commit #0c11c0254f83e90b8e9342c16cd751a19fb784e9 more details which are directly available in the online docs. Let me know if that helps.

**Comment by shimbalama** [comment]
Hi All,

I appreciated your prompt response here. Your improved docs have helped,
however, I'l still unable to upload to PyPI.

I'm sure that they make perfect sense to real devs like you, unfortunately
for me I don't have the background to be able to follow. I am a
bioinformatician (geneticist who writes basic python). I'm trying to be
more professional by setting up my projects with pyscaffold so I can
distribute code with Pip but I don't follow what your doing with versioning.

I followed this https://git-scm.com/book/en/v2/Git-Basics-Tagging  to set a
tag, committed and pushed it.

$git tag
v0.1.0

But git describe has this added:
$ git describe
v0.1.0-1-g15e21ae

And when I try to upload I still get this, despite having added the tag.
$ twine upload dist/*
Enter your password:
Uploading distributions to https://upload.pypi.org/legacy/
Uploading overlap-0.1.0.post0.dev1+g15e21ae-py2.py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████|
12.2k/12.2k [00:01<00:00, 6.69kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: '0.1.0.post0.dev1+g15e21ae' is an invalid
value for Version. Error: Can't use PEP 440 local versions. See
https://packaging.python.org/specifications/core-metadata for url:
https://upload.pypi.org/legacy/

Any help would be appreciated.

And regarding this line yo uadded to your docs 'If you want to upload to
PyPI you have to tag the current commit before uploading since PyPI does
not allow local versions, e.g. 0.0.post0.dev5+gc5da6ad, for practical
reasons.' If you could add a tiny demo snippet of code showing HOW todo
this I'm sure that'd be of great help to not just myself but any other
noobs who try to use your fantastic scaffold!

Many thanks in advance,
Liam

**Comment by FlorianWilhelm** [comment]
Hi @shimbalama,

`git describe` gives you a specific version identifier for the current commit and this is also what `setuptools-scm` uses which is used by PyScaffold. So in your case you have tagged the previous commit with version `v0.1.0` but then you created another commit. This is why `git describe` tells you that you are **1** commit after `v0.1.0`, as shown in v0.1.0-**1**-g15e21ae. 

What you can do about is either tagging the current commit with version `v0.1.1` so that `git describe` will return `v0.1.1` without any local version suffix or you create a temporary branch that points to `v0.1.0`. You can also always check what PyScaffold does by calling `python setup.py --version`. 

I am glad that you like PyScaffold and it will surely help you to become more professional in your Python coding. 

If it still does not work, please send me the output of `git log` or better make a screenshot of `gitk --all`.

**Comment by shimbalama** [comment]
Thanks. Very helpful!
