### ISSUE TITLE
Lazy contents for `define_structure` / `create_structure`

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#237]
Right now, PyScaffold keeps an in-memory representation of the entire project structure, and all the associated files, which is not very efficient. Moreover, if we check the [`structure.py`](https://github.com/pyscaffold/pyscaffold/blob/master/src/pyscaffold/structure.py), we can see that calling a function with `opts` as an argument is the de-facto standard.

### Proposal
We can accept a function in the dictionary representation. Therefore, any of the following would be accepted:

```python
struct = {
'file1': function,
'file2': (function, metadata),
}
```

#### Function Signature
For the sake of completeness and to avoid future change of the APIs, I believe the following signature is very complete and allows for max flexibility:

```python
def <function_name>(path, opts, previous_content=None):
    """Generate contents for a file in the project structure

    Arguments:
        path(os.PathLike): where the generated contents will be written to
        opts(dict): PyScaffold's options
        previous_content(str): if an existing file exists, the contents of that file will be passed, otherwise ``None``.
    Returns:
        str: Contents that will be written by PyScaffold on ``path``
    """
```

This enables a series of new scenarios like:
- appending contents to existing files
- removing sections of existing files
...

**O.B.S.:** Requires structure manipulation helpers to be updated accordingly (with potential changes in API).

#### Backward Compatibility
This change can be done in a disruptive way by enforcing functions (and therefore take advantage of the 4.0 release #235 to change the APIs/docs), or in a backward-compatible way by accepting all the following forms:
```python
structure = {
'file1': function,
'file2': 'string',
'file3': (function, metadata),
'file4': ('string', metadata),
}
```
We already loop through all the components, normalizing `'string'` to `('string', None)`, we can easily do the same, normalizing `function` to `(function, None)` and `('string', None)` to:
```python
(lambda *_, **__: 'string', None)
```

**Comment by FlorianWilhelm** [comment]
I think that's an interesting idea... and I see that you like complexity ;-) The amount of data in memory should really not be the problem, I guess we are talking about less than 1 MB for keeping the structure of the template in memory. Also right now, I really like how easy debugging is... you just use `embed()` and look at the current state of the `struct` but in case of lazy evaluation debugging would be much harder I guess. Even now we have already a lot of complexity and in some issues users of PyScaffold showed interest in writing an extension but gave up after a while... one even switched to Cookiecutter because it is easier. For that reason I would rather refrain from putting more complexity in it.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm that is fair :)

Can I ask you something, what is this `embed()` trick you have mentioned?

**Comment by FlorianWilhelm** [comment]
@abravalheri. It's basically similar to `import pdb; pdb.set_trace()` or since Python 3.7 adding `breakpoint()` to a certain line. The Python program runs to that point and drops into an interactive shell. If you don't want a debugger but rather just the familiar IPython interpreter you can do instead `from IPython import embed; embed()` add any line and just look into the current state of the `struct` variable for instance. I often use `embed()` but I guess I should get more used to the debugger.

**Comment by abravalheri** [comment]
Oh, I see IPython.
Thanks @FlorianWilhelm, very useful trick!
