### ISSUE TITLE
Remove pytest-runner setuptools integration

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#245]
Recently pytest-dev/pytest#5546 was merged with a discussion about not recommending pytest-runner integration with setuptools.

Does this affect PyScaffold in any sense?

**Comment by FlorianWilhelm** [comment]
@abravalheri, good point. Personally, I don't use `python setup.py test` at all anymore but run `py.test` or `tox` directly. If this is now recommended I would also be in favour of just dropping the runner. Would `doctest` still work? Would we lose anything else? We should then also remove it from the documentation.

**Comment by abravalheri** [comment]
I am under the impression that we would need to create a explicit tox testenv for `doctest`.
Something like this: https://ofosos.org/2019/01/06/doctest-travis/

I think that is the main drawback, isn't it? I don't think we have anything extra to loose...

**Comment by FlorianWilhelm** [comment]
Agreed. Judging from the source code of ptr, it's not responsible for the `doctest` command of `setup.py` but it's coming from Sphinx. So we could just remove ptr and state it in the `Changelog.rst` as well that we dropped it. A unit test that `doctest` still works would be nice but not really necessary since Sphinx registers this and we are in no way messing with this.

**Comment by jayvdb** [comment]
setuptools has also deprecated `test`. https://github.com/pypa/setuptools/issues/1684

**Comment by FlorianWilhelm** [comment]
Okay, then the decision is made. Let's remove it in version 4.0 from the docs and als the py.test runner contrib package. I am quite happy with this since it will reduce the code and complexity.  I haven't used `python setup.py test` for ages and always call `py.test` directly. 

Any volunteers to provide a PR for the `v4.0.x` branch?
