### ISSUE TITLE
Howto switch to 'guess-next-dev' versioning scheme?

### ISSUE THREAD

**Issue by ralhei** [pyscaffold/pyscaffold#267]
It seems that pyscaffold is setup in a way that setuptools_scm produces version numbers according to the 'post-release' style, i.e. a version generated by `python setup.py --version` looks like `0.1.0.post0.dev1+ga188051`.

According to the setuptools_scm docs the 'guess-next-dev' should be the default, so I would expect a version number like `0.1.0.dev1+ga188051`. 

How can I tweak my setup generated by pyscaffold to obtain this (postN-less) version number?

**Comment by FlorianWilhelm** [comment]
You can just pass whatever configuration option you would pass to the `use_scm_version` parameter of `setup` within `setup.py` as `use_pyscaffold` parameter.

So instead of 
```python
setup(use_pyscaffold=True)
```
you would write
```python
setup(
    use_pyscaffold={
        "root": "..",
        "relative_to": __file__,
        "local_scheme": "node-and-timestamp"
    },
)
```
and specify whatever kind of configuration you want for setuptools_scm. It should also work putting this inside `setup.cfg` as explained by setuptools_scm for recent setuptools versions.

**Comment by ralhei** [comment]
> You can just pass whatever configuration option you would pass to the `use_scm_version` parameter of `setup` within `setup.py` as `use_pyscaffold` parameter.

So, this indeed was a good advice, the following did the job:
```
setup(use_pyscaffold={'version_scheme': 'guess-next-dev'})
```
> 
> and specify whatever kind of configuration you want for setuptools_scm. It should also work putting this inside `setup.cfg` as explained by setuptools_scm for recent setuptools versions.

For some reason the setuptools_scm docs are very sparse about this ... I couldn't figure out which section to use for this (`[options]`?)  and how to put it there ...

> 
> Be aware that in your example the version order is `0.1.0.dev1+ga188051 < 0.1.0 < 0.1.0.post0.dev1+ga188051 < 0.1.1`. If you already have a tag setuptools-scm should come up with something like`0.1.1.dev1+ga188051` which I find a little presumptuous since maybe you are working on a feature release and not a bugfix.

Okay, that's a good point. However the `postN`notation should also not address a feature release. According to [PEP 440](https://www.python.org/dev/peps/pep-0440/#id28) its meaning is: "_Some projects use post-releases to address minor errors in a final release that do not affect the distributed software (for example, correcting an error in the release notes)._"

So actually none of the both approaches is really optimal ...  the best solution would be if one could configure the computation of the 'next-release' number in a more sensible way. 

However I guess this is beyond the scope of this issue, so we do not need to dive deeper into this.

**Comment by FlorianWilhelm** [comment]
I totally see your point and when I decided on the versioning scheme I had exactly your thoughts. On the one hand from my point of view one should neither increase automatically MAJOR, MINOR nor the BUGFIX part of the version since git cannot possibly know if you are working on a breaking change, a feature or some fix. On the other hand, the automated generated version needs to be larger than the last tag and the `post0.devN` suffix does exactly this. 

For several reasons I find the solution after using it many years not bad because:
* when CI/CD build the package you can just move it to some testing index to keep them separated from stable releases
* most of your users will never deal with those `post0.devN` releases but only with stables releases, 
* since I never saw official, stable `post` releases in the wild, the chance of a conflict or misconception is neglectable. 

As always, I am happy for new suggestions. PyScaffold is all about conventions and best practices, for those reasons the default configuration can be changed but I would not force the burden on the user of PyScaffold to come up with a proper scheme themself. 

BTW, have you read my [blog post about packaging, versioning and CI](https://florianwilhelm.info/2018/01/ds_in_prod_packaging_ci/)?

Can you close the ticket if you are fine with the solution provided?

**Comment by ralhei** [comment]
Will close it. Thanks for all the explanations above, and the link to your blog entry.

ps: Grüße von Gaggenau nach Karlsruhe ;-)
