### ISSUE TITLE
Add extra features after project creation

### ISSUE THREAD

**Issue by amanjeev** [pyscaffold/pyscaffold#314]
## Describe your use-case
- I have an existing codebase that was generated using `pyscaffold`/`putup`
- I forgot to add `--tox` and `--travis` to it in the beginning

## Describe the solution you would like to see for your use-case
I would like to run extra `putput`? command to add `tox` and `travis` etc. after the project generation.

**Comment by abravalheri** [comment]
Hello @amanjeev, this should be possible in the latest versions of PyScaffold via the ``--update`` option (its is definitely something that will be there in v4, when we release it :P).

Can you try the following?
- commit all the pending changes
- ``cd ..``
- ``putup --update --tox --travis PROJECT_FOLDER`` (you might want to repeat some of the flags you used before, e.g. license, since this feature is not 100% complete in v3)
- ``git diff`` and final adjustments of something that might have got overwritten...

I hope it helps.

**Comment by amanjeev** [comment]
@abravalheri thank you for your quick response. :) 

Yes, I am on the latest version (3.2.3) and I actually was able to run the `putup --update --tox ..` command. It adds the files and does overwrite some existing stuff which can be `git reset` later easily or something like that. 

For V4, would the behaviour stay the same? As in, would it still overwrite the existing files if you run `putup --update` on an existing project with flags like `--tox`? I was hoping to avoid that kind of behaviour but if it does stay the same maybe we can add a warning before `--update` is run? 

Forgive me for thinking out loud, I understand you may have thought these through already. By no means, I intend to preach to the choir. :)

**Comment by abravalheri** [comment]
Hi @amanjeev, happy that it worked (I will close the issue just to flag that it was solved, but we can keep discussing here normally).

This update behaviour would pretty much stay the same in v4, the main difference is that `cd ..` would not be required :P  (we are calling this "in-place updates" ).

So the way PyScaffold works is that we mark files as "non overwritable" or "skipable" during updates. In some cases (such as `setup.cfg`, we even go an extra mile and "merge" the updates into the current state of the file).

You can see how the files are marked in v4 (for the time being) [here](https://github.com/pyscaffold/pyscaffold/blob/v4.0.x/src/pyscaffold/structure.py#L88).
If you have any feedback or more files that should not be updated, please let us know.

Probably we won't show an warning since the documentation describes the procedure (and how to revert) in detail, but PyScaffold already shows you a log on everything that is happening when you use the verbose flags, so you can see the files being written to disk.
