### ISSUE TITLE
fail to run make latextpdf

### ISSUE THREAD

**Issue by codepage949** [pyscaffold/pyscaffold#330]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```console
$ conda create --name sample python=3.6
$ conda activate sample
$ pip install sphinx-intl
$ putup sample
$ cd sample/docs
$ make latexpdf
```

**Please provide the full traceback.**
```console
...
The LaTeX files are in ../build/sphinx/latex.
Run 'make' in that directory to run these through (pdf)latex
(use `make latexpdf' here to do that automatically).
make patch-latex
make[1]: Entering directory '...'
find _build/latex -iname "*.tex" | xargs -- \
	sed -i'' 's~includegraphics{~includegraphics\[keepaspectratio,max size={\\textwidth}{\\textheight}\]{~g'
find: ‘_build/latex’: No such file or directory
sed: no input files
make[1]: *** [Makefile:117: patch-latex] Error 123
make[1]: Leaving directory '...'
make: *** [Makefile:130: latexpdf] Error 2
```

**Please provide any additional information below.**

fixing like below solve the problem.

[before]

```sh
# docs/Makefile
...
patch-latex:
	find _build/latex -iname "*.tex" | xargs -- \
...
```

[after]

```sh
# docs/Makefile
...
patch-latex:
	find $(BUILDDIR)/latex -iname "*.tex" | xargs -- \
...
```

## Versions and main components

* PyScaffold Version: 3.2.3
* Python Version: 3.6.12
* Operating system: debian 10 buster
* How did you install PyScaffold: pip

**Comment by abravalheri** [comment]
Hi @codepage949, thank you very much for reporting.

I believe this issue is already solved in the latest commit, since we basically re-wrote the whole Makefile. Therefore the fix will be available in the next released version.

If you can, by any means, install the project from the source code and give it a try, you should not see the error message next time you create a new project and try to build the docs.

```bash
$ git clone https://github.com/pyscaffold/pyscaffold.git
$ cd pyscaffold
$ python setup.py egg_info --egg-base .
$ python setup.py develop
```

For the time being, I will close this issue, but if it still persists, even using the latest code, please fell free to reopen this issue with the updated info.
