### ISSUE TITLE
Dependency of tox doctests on docs/requirements.txt

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#351]
I have overlooked in PR #340 that also `tox.ini` depends on a requirements.txt for RTD. Should we then rather keep `docs/requirements.txt` instead of `docs/environment.yml`? Otherwise one would have to keep track of Sphinx dependencies at several places.

**Comment by abravalheri** [comment]
Umm, tricky. In v4, my idea was to use `tox` as a way of centralising all the tasks someone would previously run with `python setup.py` (e.g. `python setup.py {docs,bdist,test}`). So the users can quickly run `tox -av` instead of `python setup.py --help` and see all the tasks that are available.

The reason why tox.ini uses `docs/requirments.txt` is to be able to run `tox -e docs`.

What would be the advantages of using a `docs/environment.yml` for RTD? I suppose it can control the correct Python version?
If we want to keep the advantages of using a conda environment for RTD, could we use something like:

```yaml
- pip:
    - -r file:requirements.txt
```

in `docs/environment.yml` (and then avoid double book keeping)?

**Comment by FlorianWilhelm** [comment]
Cool idea, didn't know that this works. Since the Python version for RTD can also be controlled in `.readthedocs.yml` we actually use nothing compared to `environment.yml`. So maybe it was just my preference of Conda that drove me to this. I think we can just use `docs/requirements.txt` and everything should work, also tox.

**Comment by FlorianWilhelm** [comment]
This seems to be fixed with the last PR.
