### ISSUE TITLE
Create a pyscaffold-demo repository

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#358]
As pointed out by @FlorianWilhelm, it is nice to have a repository that was generated by PyScaffold so new comers can have a look and see what their project would look like if they generate it via `putup`. This repository could be automatically updated (`putup --update --force .`) everytime we have a new release via github actions.

**Comment by FlorianWilhelm** [comment]
@abravalheri: The demo repo was created as [pyscaffold-demo](https://github.com/pyscaffold/pyscaffold-demo). It was automatically generated by the Github Action `Make Demo Repo`. This action can be called manually by clicking "Run workflow" in the web GUI and it will also run for all created tags if they are on master. 

Now we only need to think about how we add this in the documentation. BTW, I had to push directly to master since this seems to be the only way to test Github actions.

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm
