### ISSUE TITLE
Should we use Github Actions to publish all the extension packages?

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#365]
Hi @FlorianWilhelm what do you think about using the same technique to publish all the extension packages (and maybe even configupdater) to PyPI? I suppose it will not consume loads of GA "build minutes" so it could be doable...

If we go for that, maybe `secrets.PYPI_PYSCAFFOLD_GITHUB` (or we create another account) could be shared as an [organisation secret](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-organization). so we can reuse it for all the projects?

**Comment by FlorianWilhelm** [comment]
Hi @abravalheri, I think that's an awesome idea as I am growing more and more fond of Github actions :-) We could more or less copy the `publish-package` workflow scripts to any repository we want within the PyScaffold Organisiation. I moved the secret from the realm repository to organisation so that it is available for all repos. 

I also added the `API_GITHUB_TOKEN` to `pyscaffoldext-dsproject` so that I can also update the demo project `dsproject-demo` for it the same way we do it now for PyScaffold.

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm, I added the `PyScaffold_Github` user to the repositories I have access on PyPI. When I have some time I will copy the publish-package to the extensions (I suppose it will be very handy and make it easier to develop the extensions).

Should we add the template of this action to `pyscaffoldext-custom-extension`?
Another doubt: in the default tox.ini template, I have `tox -e clean,build,publish` tasks that could be used in the action. Is it better to keep using `python setup.py` or use those tox tasks (which in turn rely on the new `build` module from PyPA)?

Enjoy new years eve!

**Comment by FlorianWilhelm** [comment]
Thanks @abravalheri, are there any repos for which you are lacking access? 

Good idea, we could add it to `pyscaffoldext-custom-extension`, especially since we are so far the most frequent users as it seems :-) 

I am not sure what the difference between `tox -e build` and `python setup.py sdist` is? What I like about the current solution is that we call `dists` which is defined in `setup.cfg` as `sdist` and `bdist_wheel`, since some users asked for source dists but also wheels. Does tox build maybe only create source packages? So `publish` is using the same way of publishing as `twine`? I am only asking because `python setup.py upload` doesn't work correctly anymore. Also, twine has `twine check` which makes sure that the metadata is correct. If all that is supported by tox we could also change. Would tox then first start to build a virtual environment within the conda environment?

**Comment by abravalheri** [comment]
I think I have access to all of them (maybe not on readthedocs).

Uummm, I think the `build` package uses exclusively PEP 517/518 and produces only wheels, and `tox -e publish` is using exactly the same techniques (including the check). But, after your explanation I don't see many advantages in changing, so we better keep using `python setup.py dists` and the current configurations 😝

**Comment by FlorianWilhelm** [comment]
Hm... makes me think. Do we still need source distributions for PyScaffold version 4.0? I think we needed it until version 3.x because `setup_requires` can only handle source distributions as far as I remember. Since we no longer depend on this we might stop generating those? Or should we rather wait for version 5.0 to get rid of source distributions? I think for version 4.0 you mention in the docs that one can roll back to the old behavior by defining `setup_requires=pyscaffold` again.

**Comment by abravalheri** [comment]
I think the docs mention `setup_requires` for `setuptools_scm`. In version 4, PyScaffold should not be a build time dependency anymore (maybe I forgot something in the docs that need correction)?

So yes, I believe we could try to generate only wheels and wait until someone asks for the source distribution?

Btw, I just found out that we can generate `sdists` with `build` from PyPA. In fact running `python -m build . -s -w` would generate both `sdist` (`-s`) and `wheel` (`-w`). If we omit the flags (the way it it right now in `tox.ini` it generates the `wheel` by default).

I am doing some investigation right now in pyscaffoldext-custom-extension.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, it seems that if we use `tox` directly we might save some precious "GA minutes" :P.
I tried some things out in the `pyscaffoldext-custom-extension` after conda was taking too long to create the environment in my computer.

In https://github.com/pyscaffold/pyscaffoldext-custom-extension/actions/runs/456601471 you can see that `tox` takes 36s to upload the package to PyPI, while the conda-based action takes 1m 46s to create the environment... (there are still some errors with conda that I would have to debug).

**Comment by FlorianWilhelm** [comment]
Thanks @abravalheri, this might really be much smarter than what I did. I would maybe only keep the conda way of doing things for `pyscaffoldest-dsproject` since this extension is all about using conda anyway.

**Comment by FlorianWilhelm** [comment]
Regarding your former statement. I would also go for wheels only until someone complains and has a good reason for asking for source distributions. Maybe we should also state this much more prominently in our docs, e.g. we have right now
"... you can execute `python setup.py sdist` or `python setup.py bdist_wheel` (recommended)." We could reformulate this "... you can execute `python setup.py bdist_wheel` to generate a modern wheel distribution. Source distributions (sdist) and binary distributions (bdist) are no longer recommended and may cause problems."

**Comment by FlorianWilhelm** [comment]
Ah and one could then also remove 
```
[aliases]
dists = sdist bdist_wheel
```
from `setup.cfg` in the version 4 release. Right?

**Comment by abravalheri** [comment]
I think now all the extensions have the GA set up.

Something that I did by mistake was to publish a tag first on [pyscaffoldext-travis](https://pypi.org/project/pyscaffoldext-travis/)  before uploading a package to PyPI manually first, which means that PyScaffold_Github is the only owner/maintainer of the packages and that @FlorianWilhelm and I cannot manually change it 😝. Sorry for the silly mistake.

**Comment by FlorianWilhelm** [comment]
No problem, errors happen :-) You should see an invitation to the pypi package now.

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm
