### ISSUE TITLE
Add semver example in generated setup.cfg

### ISSUE THREAD

**Issue by CarliJoy** [pyscaffold/pyscaffold#400]
## Describe your use-case
Currently I am always looking in the pyscaffold own setup.cfg to figure out how to provide semver like dependencies (which a best parctise).
Also I know that a lot of not so experienced dev aren't familar with it, so it would be good to nose point them to it ;-)

## Describe the solution you would like to see for your use-case
Simply convert in `src/pyscaffold/templates/setup_cfg.template`
```
# Add here dependencies of your project (line-separated)
# TODO: Remove conditional dependencies according to `python_requires` above
install_requires =
```
to 
```
# Add here dependencies of your project (line-separated)
# TODO: Remove conditional dependencies according to `python_requires` above
install_requires =
# Example:
# install_requires =
#    requests>=2.2,<3.0
# Note this makes sure to not run into api brakes,
# assuming the required packages follows Sementic versioning
# see https://semver.org/ for more information
```

PS: I don't understand the todo

**Comment by FlorianWilhelm** [comment]
Thanks @CarliJoy, I think that's a good idea. Maybe we could change the text to something like
```
# install_requires =
#    requests>=2.2,<3.0
# Version specifiers like >=2.2,<3.0 avoid problems due the
# API changes in new majors versions. This works if the required
# packages follow Semantic versioning. For more information,
# check out https://semver.org/.
```

I am also not quite sure what
```
# TODO: Remove conditional dependencies according to `python_requires` above
```
means. Might be some reminiscent of version 4.0 changes, we should remove.

**Comment by abravalheri** [comment]
Regarding the TODO comment, in [v4](https://github.com/pyscaffold/pyscaffold-demo/blob/63fe1cf4ee5cc969c34f80ea5d749ed83bb19c82/setup.cfg#L47) we have the following lines being generated:

```cfg
install_requires =
    importlib-metadata; python_version<"3.8"
```

If `python_requires = >=3.8`, then this dependency is never being activated and should be removed...

**Comment by FlorianWilhelm** [comment]
@abravalheri: What if we would set 
```
python_requires = >=3.8
```
as a sane default in version 4.0 and have a comment:
```
# If your project requires or needs to support Python < 3.8, please add
#         importlib-metadata; python_version<"3.8"
# to `install_requires =` below.

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm, I think setting `python_requires >= 3.8` by default is a bit complicated...
it would probably break our system tests or at least require them to be redesigned since we test PyScaffold for all currently supported Python releases (in general I like the idea of testing PyScaffold accross all versions bigger than [the oldest officially supported version](https://www.python.org/downloads/))...

The first proposal looks easier to implement. We can give the second approach a shot, but inline comments might fail due to the way the dependencies are processed in [dependencies.py](https://github.com/pyscaffold/pyscaffold/blob/master/src/pyscaffold/dependencies.py).

I might attempt to compose a PR for the changes discussed here during the weekend, but if any of you wants to go ahead please feel free. I think we can ship these changes to the final v4, since they are basically comments anyway...

Thanks again for pointing this out @CarliJoy!

**Comment by FlorianWilhelm** [comment]
I'll prep a PR for discussion

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm for the PR, let's close this issue for now.
