### ISSUE TITLE
Default git branch name

### ISSUE THREAD

**Issue by stephenlutes** [pyscaffold/pyscaffold#575]
In the past few years, there has been a move to set default branch names in git as 'main' instead of 'master'. We are at a point where if you create a repository with README in GitHub, they name the default branch 'main'. While switching to that naming scheme may not be advised for default, there is the possibility of including a tag that would allow for setting the default branch name after the initial commit.

For instance being able to have a tag --branch-name [NAME] as part of the putup command. This should be a fairly straight-forward addition, as it should only require checking the tag, and if it exists, running a second git command.

I am more than happy to look into this, and create a pull request, if it is something that can be moved forward on.

**Comment by abravalheri** [comment]
Hi @stephenlutes thank you very much for bringing this up!

I think it would be a nice addition to PyScaffold and I would be more than happy to review a PR.

If you want to give it a go, and are new to PyScaffold development, I would recommend having a look at our [developer guide](https://pyscaffold.org/en/stable/dev-guide.html) and [extension docs](https://pyscaffold.org/en/stable/extensions.html).

Please let me know if you need any help!

**Comment by abravalheri** [comment]
Maybe `--default-git-branch` conveys the meaning better (but that would definitely require a short form too).

@FlorianWilhelm any thoughts?

**Comment by FlorianWilhelm** [comment]
Hi @stephenlutes, thanks for your input. I am not sure this is really a common use-case and having a flag for it in `putup` seems a bit like an overkill. To solve this issue, we could for instance mention in the docs that by setting
```
git config --global init.defaultBranch <name>
```
you can easily set the default branch of a project scaffold set up with PyScaffold. If you forgot it, you can change it afterwards easily with `git branch -m <name>`. By default I think it's still `master` but many want `main` nowadays. I would actually prefer to solve this with extra documentation and let git do the right thing instead of including it in PyScaffold itself. It just doesn't feel like the right place for something like this although it would be quite easy to implement.

**Comment by abravalheri** [comment]
Always wise @FlorianWilhelm

**Comment by stephenlutes** [comment]
This does work for me personally. I will go ahead and close the issue. However, I do believe there are still use cases for having a flag for this. For instance, someone who may name their personal default branches one thing, but need to use a different branch name for a community project or work. While not necessary right now, I think it is something to keep in mind down the road.

**Comment by FlorianWilhelm** [comment]
@stephenlutes, cool, then let's leave this open as a reminder to add this to the docs and maybe even a FAQ answer. I can do this if I find some time.

**Comment by FlorianWilhelm** [comment]
It's fixed in PR #577.
