### ISSUE TITLE
GitHub actions seems to still be using sdist - should this be adjusted to bdist_wheel?

### ISSUE THREAD

**Issue by sgbaird** [pyscaffold/pyscaffold#684]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**

The following command would probably work.
```python
putup --github-actions
```

See [this GitHub actions runner](https://github.com/sparks-baird/self-driving-lab-demo/actions/runs/3679664930/jobs/6224375040).

I got a "File too large" error when trying to publish to PyPI because files other than what's in `src` are added to the distribution. I came across https://github.com/pyscaffold/pyscaffold/issues/404 which mentioned the use of `sdist` vs. `bdist_wheel`, where the latter is recommended. Checking the GitHub actions log, I'm seeing that `sdist` is being used during:
```python
pipx run --spec tox==3.27.1 tox -e clean,build
```
which calls:
```python
python -m build
```
where [`build`](https://pypi.org/project/build/) is a Python package and produces the message:
```python
...
Getting build dependencies for sdist...
...
```

**Please provide the full traceback using the `--very-verbose` flag.**
```python
# [The error output here]
```

**Please provide any additional information below.**
I'd like for only `src` files to be added to the distribution by default.

## Versions and main components

* PyScaffold Version: 4.2.3.post1.dev10+g7a0f254
* Python Version:
* Operating system: Windows
* How did you install PyScaffold: (conda/pip) I don't remember, but can check if it's pertinent

**Comment by abravalheri** [comment]
Hi @sgbaird , when using `build` without any flags both `sdist` and `wheel` are generated by default (the `wheel` file is generated from the `sdist`, to improve testability, this is a common practice in the ecosystem).

The `sdist` works more or less as a snapshot of the repository, so it will naturally include more files than the wheel (e.g. docs, tests, auxiliary scripts etc). In general people preparing packages for Linux distributions really like this behaviour...

If your `sdist` is too big for being uploaded, maybe you can consider not building/submitting the `sdist` for that particular project.

Alternatively you can also review the `.gitignore` file to not store big files in the repository, or add a [`MANIFEST.in`](https://packaging.python.org/en/latest/guides/using-manifest-in/) to remove some of the directories from the `sdist` (PyScaffold already sets up `setuptools-scm`, so I believe that you don't need any `include` or `graft` instructions, just `prune` and `exclude`).

But in general, I believe that this is not a gener problem for all types of packages...
@FlorianWilhelm , this issue seems to be related to the existence of folders with bug files in the `dsproject` extension. Is there anything specific we should be doing for that extension?

**Comment by sgbaird** [comment]
Thanks for clarifying! I'll close the PR

**Comment by FlorianWilhelm** [comment]
Sorry for coming so late to the party. Actually, I hope that `sdist` packages are hopefully soon a thing of the past and going back to a `MANIFEST.in` would surely complicate things for newcomers.

@abravalheri : What if we drop it all together by default as @sgbaird suggested?

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, this is certainly possible, but I would like to share this thread https://discuss.python.org/t/should-sdists-include-docs-and-tests/14578 as a reading material for this discussion.

Some distribution repackagers (the ones that create OS-specific packages for ubuntu, arch, homebrew, etc...) really like to work from the source instead of the built wheel. And also there is some level of consensus that submitting `sdists` to PyPI whenever possible is a good thing...

Usually we can place these things in a spectrum:

```
reposity -->
sdist (may contain *some* level of compilation/optimization, e.g. Cython => c, but it is still platform independent and preserves development-time files like tests, docs) -->
wheel (platform-specific, may contain compilated/optimized files) -->
installed files (platform-specific, contain compiled/optimized files, including .pyc)
```

**Comment by FlorianWilhelm** [comment]
Thanks @abravalheri, I didn't know that the intention of sdist is to actually include everything from the repository itself. 

What if we add a comment that says something like:
```
# use the following line instead if you want to publish only wheel files
# run: pipx run tox -e clean,build -- --wheel
``` 
or the other way around with wheel and sdist. Just a thought. I am really no expert regarding the practical usage of sdists.

**Comment by abravalheri** [comment]
@FlorianWilhelm I created something along these lines in #694.

**Comment by abravalheri** [comment]
@sgbaird, I think that #694 addresses the main concerns that are captured in this issue.

Now, [there is an entry in the FAQ](https://pyscaffold.org/en/stable/faq.html#common-doubts-about-sdist) explaining the approach for sdists, which also indicates a possible workaround for publishing the package when the `sdist` is too big.

As discussed in [this thread](https://discuss.python.org/t/should-sdists-include-docs-and-tests/14578), `sdists` are expected to contain docs, tests, and everything that is used during development time.

If you have files in your repo that are not used (or that are just optional) during development time, you can still use the approach I mentioned [here](https://github.com/pyscaffold/pyscaffold/issues/684#issuecomment-1347489133), i.e. `MANIFEST.in` just as a complement to `setuptools-scm`. I did not include this part in the FAQ because [the process may confuse newcommers as argued by Florian](https://github.com/pyscaffold/pyscaffold/issues/684#issuecomment-1381629739).

If you are using data files, you can also consider using a solution like [DVC](https://dvc.org/) to avoid storing big files in the git repo.

For now I will close this issue because it looks completed from my point of view, but please let me know if you have a different opinion. We can re-open this issue.
