### ISSUE TITLE
Can't publish basic my_project using tox -e publish successfully.

### ISSUE THREAD

**Issue by laraws** [pyscaffold/pyscaffold#733]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
I used `putup my_project` to create a project and then use some tox comamnd to publish it.
```bash
putup my_project
tox -e docs  # to build your documentation
tox -e build  # to build your package distribution
tox -e publish  -vvv
```

**Please provide the full traceback using the `--very-verbose` flag.**
When I run `tox -e publish  -vvv`, the error shows below at last.
```
Uploading my_project-0.0.post1.dev1+ga5050e2-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 kB • 00:00 • ?
WARNING  Error during upload. Retry with the --verbose option for more details.                                                                                                                                    
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/                                                                                                                                             
         '0.0.post1.dev1+ga5050e2' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata for more information.  
```

**Please provide any additional information below.**

When I run `putup my_project` to create a project and then run tox commands to build and publish it, the error show above. How can I push it successfuly? 

## Versions and main components

* PyScaffold Version: PyScaffold 4.5
* Python Version: Python 3.11.4
* Operating system: Ubuntu 20.04.6 LTS x86_64
* How did you install PyScaffold: pip

**Comment by abravalheri** [comment]
Hi @laraws, the hint is in the error message: `Can't use PEP 440 local versions.`

PEP 440 defines "local segment" as the `+<something>` part in the version specifier. So in your case, the complete version is `0.0.post1.dev1+ga5050e2` and the local segment is `+ga5050e2`.
It is a PyPI policy to not accept such local segments, so you have to rebuild your project in a way that it does not end up with a `+<something>` local segment in the version.

Now, for why you have this local segment in your build: the version specifier is automatically derived from git (using [`setuptools-scm`](https://pypi.org/project/setuptools-scm/)); by looking at your version I would guess you seem to be trying to build a version that has not been tagged yet[^1].

For the version string to be "clean" you need to build exactly after tagging a version, no commits in between. You also need to make sure your working directory is "clean of changes", i.e. `git status` will say `nothing to commit, working tree clean`.

We have an entry on our [FAQ](
https://pyscaffold.org/en/stable/faq.html#best-practices-and-common-errors-with-version-numbers) on "clean versions", maybe that is helpful to you.

[^1]: If you commit after doing a tag, in `setuptools-scm` eyes that is a different version, because you did changes...

**Comment by laraws** [comment]
> Hi @laraws, the hint is in the error message: `Can't use PEP 440 local versions.`
> 
> PEP 440 defines "local segment" as the `+<something>` part in the version specifier. So in your case, the complete version is `0.0.post1.dev1+ga5050e2` and the local segment is `+ga5050e2`. It is a PyPI policy to not accept such local segments, so you have to rebuild your project in a way that it does not end up with a `+<something>` local segment in the version.
> 
> Now, for why you have this local segment in your build: the version specifier is automatically derived from git (using [`setuptools-scm`](https://pypi.org/project/setuptools-scm/)); by looking at your version I would guess you seem to be trying to build a version that has not been tagged yet[1](#user-content-fn-1-57765815a6613ddea3c4d83ea1499238).
> 
> For the version string to be "clean" you need to build exactly after tagging a version, no commits in between. You also need to make sure your working directory is "clean of changes", i.e. `git status` will say `nothing to commit, working tree clean`.
> 
> We have an entry on our [FAQ](https://pyscaffold.org/en/stable/faq.html#best-practices-and-common-errors-with-version-numbers) on "clean versions", maybe that is helpful to you.
> 
> ## Footnotes
> 1. If you commit after doing a tag, in `setuptools-scm` eyes that is a different version, because you did changes... [↩](#user-content-fnref-1-57765815a6613ddea3c4d83ea1499238)

After successfully tagging the package, I publish it. Thank you for your answer.
